export const dataNews = [
  {
    id: 1,
    thumbnail: "https://s3.cloud.cmctelecom.vn/tinhte1/2014/12/2663849_sbm2_pc.jpg",
    title: `<h3>Doraemon: Stand by Me – Cho tất cả những ai từng là thiếu nhi.</h3>`,
    content: `<p>Đối với thế hệ 7x cuối và 8x, chắc hẳn không ai xa lạ với những câu chuyện về chú mèo máy thông minh Doraemon, Nobita và những người bạn tinh nghịch đáng yêu cùng khu phố. Có thể nói những cuốn truyện tranh trắng đen với hình ảnh ngộ nghĩnh cùng những câu chuyện về những chuyến phưu lưu qua cỗ máy vượt thời gian của Doreamon chứa đầy những kỷ niệm của thời thơ ấu. Stand by Me sẽ dành cho những ai đã từng là thiếu nhi.</p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2014/12/2663849_sbm2_pc.jpg"/> <p>Doraemon hay tiếng Việt chúng ta vẫn đọc là Đôrêmon là một bộ truyện tranh của Nhật Bản được sáng tác từ năm 1969 dành cho tuổi thiếu nhi. Tác phẩm tuyệt vời này của Fujiko Fujio (bút danh chung của 2 họa sĩ Manga Fujimoto Hiroshi và Abiko Motoo). Theo như tác giả thì sở dĩ có nhân vật Doraemon với hình dáng như chúng ta thấy vì trong một buổi chiều Hiroshi thấy con gái chơi với con lật đật, nên ông nảy ra ý định kết hợp giữa con mèo và lật đật làm tạo hình nhân vật cho Doraemon.</p> <p>Tại Nhật Bản tính đến năm 1999 đã có khoảng 100 triệu tập đã được tiêu thụ ở nước này. Bên cạnh đó với sức hút từ bộ truyện tranh không chỉ dành riêng cho thiếu nhi, có hàng ngàn tập phim ngắn được phát sóng và gần 40 tập phim dài về các nhân vật hoạt hình này. Sau Nhật Bản, Doraemon được phát hành trên khắp thế giới, đặc biệt khu vực Châu á trong đó có Việt Nam đã dành rất nhiều tình cảm và sự hâm mộ đặc biệt cho bộ truyện tranh đáng yêu này.</p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2014/12/2663850_10372978_834730476567366_7913765221691087326_o.jpg">
    <p>Đối với khán giả Việt Nam thì những năm 1990 thì những bộ truyện tranh là kênh giải trí tuyệt vời nhất mà bất kỳ đứa trẻ nào cũng mong muốn sở hữu, thậm chí việc đọc ké cũng là niềm ao ước của rất nhiều bạn, trong đó có mình J. Doraemon mở ra một chân trời hoàn toàn đẹp đẽ và tươi sáng với các thiết bị điện tử thông minh và rất lạ lẫm so với thời điểm đó, khán giả nhí có thể thả trí tượng tượng và những ước mơ bay cao theo những chiếc chong chóng tre.</p>Phim được đạo diễn bởi Yakuwa Shinnosuke - người đã từng quen mặt với các fan của Doraemon qua hai bộ phim anime "Phim Doraemon: Nobita thám hiểm vùng đất mới - Peko và 5 Nhà thám hiểm (2014) và "Phim Doraemon: Nobita và nước Nhật thời nguyên thủy (2016)". Tại Nhật, phim ra mắt đầu tháng 3 và thu hút lượng lớn khán giả đến rạp, hiện thu gần 50 triệu USD.
    <img src="https://s3.cloud.cmctelecom.vn/tinhte1/2014/12/2663851_IMG_2141.jpg"/><p>Với Doraemon: Stand by Me, là bộ phim hoạt hình 3D đầu tiên về Doraemon, thế nên phần hình ảnh và hình dáng nhân vật rất khác khác biệt so với những tập phim của phiên bản 2D đã chiếu.Về cốt truyện, Stand by Me không dựa trên một tập phim hay chuyến phưu lưu cụ thể nào của mèo máy và các bạn mà lắp ghép khéo léo những câu chuyện ngắn thành một nội dung xuyên suốt. Bộ phim kể về lý do tại sao mèo ú xuất hiện bên cạnh Nobia hậu đậu, ngốc nghếch nhưng tốt bụng. Qúa trình lớn lên của đôi bạn với rất nhiều những kỉ niệm vui buồn cho đến khi Nobita cảm thấy thật sự hạnh phúc. Hoàn thành được sứ mệnh của mình, cũng là lúc mèo máy phải trở về tương lai</p><p>Stand by Me vẫn giữ nguyên phong cách vốn có của bộ truyện tranh gốc. Hài hước kiểu rất ngố, đúng theo tâm lý trẻ con. Nhẹ nhàng, trong sáng nhưng rất đỗi tình cảm. Khán giả có thể cười nghiêng ngả với những trò đùa tai quái Xeko, những trò bắt nạt có 1 không 2 của Chaien mập và hình ảnh xuka đáng yêu. Đặc biệt tạo hình của Xuka trong tương lai cực kỳ xinh đẹp và tinh tế. Ngoài ra các nhân vật như Chaiko, Đekhi và các nhân vật khác với tạo hình “cực chuẩn”, theo đúng trí tưởng tượng của mình trong phiên bản truyện tranh.
    </p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2014/12/2663851_IMG_2141.jpg/><p>Khán giả cũng dễ dàng bắt gặp những hình ảnh hết sức quen thuộc, mà chỉ cần thấy lập tức những câu chuyện xung quanh “chốn cũ” lại ùa về, một cảm giác thực sự rất khó tả. Đó là khoảng đất trống có những chiếc cống trống mà Nobita và các bạn vẫn chui ra vào, những ngôi nhà và con đường đặc trưng của xứ sở hoa anh đào, mái nhà, con chó hung dữ…tất cả đều rất gần gũi và thân quen.</p><p>Về hình hiệu ứng hình ảnh Doraemon: Stand by Me rất sống động, màu sắc tươi vui và rất sắc nét, hiệu ứng 3D trong một số khung cảnh rất nổi bật. Trong chuyến du hành đến tương lai qua cỗ máy vượt thời gian, trên đường phố với những nét đặc trưng của đất nước Nhật Bản khán giả sẽ bắt gặp rất nhiều các thương hiệu nổi tiếng của nước này, trong đó có 2 nhãn hiệu lớn là Panasonic và Toyota.Thêm một điểm cộng nữa cho bộ phim là phần lồng tiếng cho nhân vật cho cảm xúc của khán giả được thăng hoa. Vẫn là những cái tên quen thuộc đã gắn bó với các series Doraemon: Wasabi Mizuta (Doraemon), Megumi Ohara (Nobita), Yumi Kakazu (xuka), Tomokazu Seki (Xeko), Subaru Kimura (Chaien)…
    </p>`,
    createdAt: "Chủ Nhật, 06:00, 26/05/2021",
  },
  {
    id: 2,
    thumbnail: "https://kenh14cdn.com/thumb_w/620/2017/1-1490978568150.jpg",
    title: `<h3>The Boss Baby - Đáng yêu đến mức độ không thể chấp nhận được</h3>`,
    content: `<p>Tháng 3 là một tháng nóng bỏng trong năm nay, không phải chỉ vì báo hiệu mùa hè sắp đến mà do đây còn là tháng ngập tràn bom tấn. Trong khi đó thì thể loại phim cho gia đình là phim hoạt hình thì lại cực kỳ khan hiếm. Từ đầu tháng đến giờ, chỉ có duy nhất bộ phim hoạt hình của Pháp là Ballerina được công chiếu. Chính vì lẽ đó mà The Boss Baby của DreamWorks chẳng khác gì một cơn mưa đầu mùa thực sự tươi mát cho những ngày sang hè đầy oi bức.</p> <img src="https://kenh14cdn.com/thumb_w/620/2017/1-1490978568150.jpg"/> <p>The Boss Baby xoay quanh cậu bé 7 tuổi Tim đang có một cuộc sống ấm êm và hạnh phúc khi bố mẹ của cậu luôn hết mực yêu thương và chăm lo cho cậu từng cái ăn cái mặc. Không ngờ một ngày nọ Tim phải đối mặt với biến cố lớn trong đời: cậu có một đứa em "từ trên trời rơi xuống" và phải học làm anh. Phải san sẻ yêu thương vốn chỉ của riêng mình với một người mà Tim không có chút tình cảm, giờ đây với cậu bầu trời như sập đến nơi.<p>Tuyệt vọng chưa bao lâu thì Tim phát hiện ra, đứa em trai của mình chẳng những biết nói chuyện mà cậu còn có thể nói giọng của người lớn và hành động chẳng khác một đại ca xã đoàn. Bé con này nạt nộ những đứa bạn cùng lứa và thậm chí quẳng tiền vào thẳng mặt những ai không hài lòng với những việc mà cậu đang làm. Điều đáng nói là chẳng ai phát hiện điều đó, ngoại trừ cậu bé Tim. Thế là cậu nhóc quyết định tìm đủ mọi cách vạch trần đứa em trai.</p> <img src="https://kenh14cdn.com/thumb_w/620/2017/3-1490978568152.jpg" /> <p>Thật ra Nhóc Trùm làm "gián điệp" trong gia đình có các nhân viên làm việc ở Công ty Cún là để tìm mọi cách ngăn chặn sự ra mắt của một loài cún cưng có khả năng tước đoạt tình yêu của mọi người dành cho các em bé. The Boss Baby đã vẽ nên một bức tranh mới mẻ tạo cảm giác hứng thú, tò mò cho người xem. Bộ phim cũng phần nào phản ánh đúng thực tế khi ngày càng nhiều người ngần ngại sinh đẻ và thay vào đó lựa chọn nuôi nấng thú cưng.</p>
    `,
    createdAt: "Chủ Nhật, 06:00, 26/05/2021",
  },
  {
    id: 3,
    thumbnail: "https://i.ytimg.com/vi/9g6DYF8niCM/maxresdefault.jpg",
    title: `<h3>Rạp phim mùa Lễ: Binh đoàn hoạt hình "áp đảo" phòng vé, mẹ trẻ khỏi lo thiếu "quà" cho em nhỏ</h3>`,
    content: `<p>Brooklynn Prince, JoJo Siwa, Genesis Tennon, Alma Varsano, Faith Urban, và Sunday Urban là những diễn viên đảm nhận vai trò lồng tiếng cho những chú chim non sắp xuất hiện trong phần 2 của bộ phim hoạt hình dựa trên tựa game cùng tên Angry Birds. Mới đây Sony vừa tung những hình ảnh mới nhất về “lũ giặc” này trong đoạn clip mới.</p><img src="https://ss-images.saostar.vn/wwebp700/2019/07/29/5723947/4.jpg" /><p>Trong The Angry Birds Movie 2, những chú chim giận dữ không biết bay và lũ heo xanh đang lập kế hoạch đưa thịt bò của chúng lên tầm cao mới. Tuy nhiên, một mối đe dọa ập đến khiến hòn đảo của cả chim và heo đều gặp nguy hiểm. Lúc này, Red (Jason Sudeikis), Chuck (Josh Gad), Bomb (Danny McBride) và Mighty Eagle (Peter Dinklage) chiêu mộ thêm Silver (Rachel Bloom) - người chị em của Chuck để hợp tác với chú heo Leonard (Bill Hader), trợ tá Courtney (Awkwafina) và chú lợn công nghệ Garry (Sterling K. Brown) để thỏa thuận ngừng chiến tạm thời và lập thành một team để bảo vệ ngôi nhà của họ. Sony Pictures Animation's và Rovio's đã kết hợp để có thể tạo ra những hình tượng nhân vật mới với độ cute vô đối, và có vẻ như là họ đã quá thành công. Đám chim non được biết đến trong phim với cái tên The Hatchling và đã dễ dàng chiếm trọn trái tim của tất cả khán giả. Tất nhiên là bọn chúng không hề có ý định trả lại.</p><img src="https://ss-images.saostar.vn/wwebp700/2019/07/29/5723947/2.jpg" /><p>Bộ phim cũng sẽ có sự tham gia lồng tiếng của toàn các ngôi sao khác, bao gồm Jason Sudeikis, Josh Gad, Leslie Jones, Bill Hader, Rachel Bloom, Awkwafina, Sterling K. Brown, Eugenio Derbez, Danny McBride, Peter Dinklage, Pete Davidson, Zach Woods, Dove Cameron, Lil Rel Howery, Nicki Minaj và Beck Bennett.</p><img src="https://ss-images.saostar.vn/wwebp700/2019/07/29/5723947/the-angry-birds-movie-4.jpg" /><p>Trong đoạn clip, bọn chúng đang chơi trò nhập vai, và quyết định trôm đống trứng thật để khiến cho câu chuyện thêm kịch tính. Tuy nhiên, ngay khi bọn nhóc không để ý, 3 trái trứng đã bị sóng biển đánh và trôi ra xa.</p><p>3 chú chim non xuất hiện trong clip được lồng tiếng bởi Prince, Tennon và Varsano (lần lượt cho 3 chú chim Zoe, Vivi và Sam Sam). Chúng sẽ có câu chuyện của riêng mình và đương nhiên là những trò nghịch ngợm, quậy phá cũng sẽ được đưa lên một tầm cao mới.</p><p>Angry Birds 2 sẽ được ra rạp vào ngày 14/8 tới tại các rạp trên toàn quốc.</p><p>THE ANGRY BIRDS MOVIE 2: Clip chim non phá đảo đống trứng</p>`,
    createdAt: "Chủ Nhật, 06:00, 26/05/2021",
  },
  {
    id: 4,
    thumbnail: "https://s3.cloud.cmctelecom.vn/tinhte1/2016/11/3920224_moana-fallback_fde4d101.jpg",
    title: `<h3>Cảm nhận phim hoạt hình Moana: đồ họa đẹp, hay & ý nghĩa, vui nhộn, đáng xem</h3>`,
    content: `<p>Thật trùng hợp khi 2 phim bom tấn cuối năm của Disney là Doctor Strange ra mắt hồi tháng 10 và hoạt hình Moana, vừa ra mắt ngày 25/11 này lại có motif na ná nhau. Hai bộ phim là 2 thể loại khác nhau, thuộc 2 thời đại khác nhau, 2 thế giới khác nhau, 2 đối tượng khác nhau, nhưng lại cùng chung một hành trình: khám phá thế giới quanh ta không chỉ giới hạn là một vùng đất mà là những bến bờ vô tận với vô số bí ẩn không thể khám phá hết, đồng thời cũng là chặng đường để khẳng định cái tôi và hoàn thiện bản thân.</p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2016/11/3920224_moana-fallback_fde4d101.jpg" /><p>Moana (đọc là Mô-a-na), tựa tiếng Việt "Hành Trình Moana" là bộ phim hoạt hình bom tấn với kinh phí lên tới 150 triệu đô la của Disney. Phim nói về cô bé Moana 16 tuổi, con của tù trưởng Tui, trên chuyến hành trình ra biển khơi đầu tiên trong đời cùng với người bạn Maui (đọc là Mao-i) - một vị á thần ngàn tuổi - và cũng là chuyến đi giúp thay đổi số mệnh không chỉ của riêng cô mà của cả bộ lạc mà cô đang sinh sống.</p><img src="https://p4.wallpaperbetter.com/wallpaper/191/533/242/movie-moana-moana-movie-moana-waialiki-wallpaper-preview.jpg" /><p>Tại sao mình lại nói Moana giống với Doctor Strange? Thứ nhất, Moana là một cô bé 16 tuổi, tức là độ tuổi dậy thì đang có thay đổi rất lớn trong tính cách, cách suy nghĩ và nhìn nhận thế giới. Ngay từ bé, Moana đã được bà nội của mình là Sina "bơm" vô đầu những câu chuyện truyền thuyết từ hàng ngàn năm trước, vô hình chung đã hình thành trong tâm tưởng của Moana rằng cô bé là một người đặc biệt, có số phận đã được định sẵn sẽ thay đổi định mệnh của nhân loại. Đặc điểm tính cách này của Moana khá giống với Stephen Strange, người luôn tự tin vào bản thân vô cùng kiêu ngạo.
    </p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2016/11/3920223_flex_moana_waterspouts_tablet_a4e40756.jpg"/><p>Bên cạnh đó, vị á thần Maui giống với The Ancient One, người sẽ dạy cho Moana những bài học quý giá cho chuyến hành trình đầu đời, người giúp Moana trưởng thành cả về tính cách lẫn kinh nghiệm sống. Ngoài ra, cũng giống Ancient One, Maui cũng phạm một sai lầm không thể sửa đổi trong quá khứ và chỉ có Moana mới có thể giúp ông sửa chữa nó. Trải dài suốt hành trình, Maui sẽ là người giúp Moana hiểu được thế giới xung quanh cô vận hành theo cách này chứ không phải theo kiểu kia, như cô vốn xưa nay vẫn tưởng là như vậy.</p><img src="https://s3.cloud.cmctelecom.vn/tinhte1/2016/11/3920225_ynsrc65mv8y6ngh8rezk.jpg" /><p>Hành Trình Của Moana có phiên bản phụ đề và bản lồng tiếng. Có thể nói bản lồng tiếng được thực hiện tốt, các nhân vật lồng tiếng đều thể hiện tròn vai. Ban đầu thì mình không ưa giọng của bạn lồng tiếng Moana lắm, đặc biệt là khi hát bài hát chủ đề của phim (OST: How Far I'll Go) phiên bản tiếng Việt ở đoạn đầu phim có hơi gượng gạo, nhưng qua nửa phim thì mọi việc suông sẻ hơn. Mình cũng thử nghe qua bản gốc How Far I'll Go và cảm thấy là bản tiếng Việt cũng đạt 8/10 so với bản tiếng Anh.</p><p>À, phim Moana còn bất ngờ lắm, ví dụ ở chỗ phim có phong cách rất "Ấn Độ" 😁. Chúc các bạn xem phim vui vẻ!!!
    </p>`,
    createdAt: "Chủ Nhật, 06:00, 26/05/2021",
  },
];
